version: '3.9'
services:
  frontend:
    build: ../frontend
    volumes:
      - ../frontend:/app/result_build/


  db:
    container_name: database
    image: postgres:14.0-alpine
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  backend:
      container_name: backend
      build: ../backend
      restart: always
      volumes:
        - ./data/back_static:/app/data/back_static/
        - ./data/back_media:/app/data/back_media/
      depends_on:
        db:
          condition: service_healthy
      env_file:
        - .env

  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./data/back_static:/var/html/back_static/
      - ./data/back_media:/var/html/back_media/
    depends_on:
      - backend
