name: backend tests

on:
  push:
    branches:
      - main
      - develop
      - backend
  pull_request:
    branches:
      - main
      - develop
      - backend

jobs:

  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort flake8-quotes

      - name: Test with flake8
        run: python -m flake8 backend

      - name: Test with Django Unittest
        run: |
          cd backend
          python manage.py makemigrations
          python manage.py test --verbosity 2
