name: Calendar backend build workflows

on:
  push:
    branches:
      - feature/compose_ci_cd

jobs:

  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort flake8-quotes

      - name: Test with flake8
        run: python -m flake8 backend

      - name: Test with Django Unittest
        run: |
          cd backend
          python manage.py makemigrations
          python manage.py test --verbosity 2

  build_and_push_to_dockerhub:
    name: Push to Dockerhub
    runs-on: ubuntu-20.04
    needs: tests
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: calendaily
          password: cevneg-wyGne2-muwzeh
      - name: Push to Dockerhub
        uses: docker/build-push-action@v3
        with:
          context: ./backend/
          push: true
          tags: calendaily/backend:latest

  deploy_on_remote_server:
    runs-on: ubuntu-20.04
    needs: build_and_push_to_dockerhub
    steps:
      - name: executing remote ssh commands and deploy
        uses: appleboy/ssh-action@master@v2
        with:
          host: 193.107.236.224
          username: github_actions
          passphrase: Git12342807
          key: "-----BEGIN OPENSSH PRIVATE KEY-----
                b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCUViwG/k
                1P5HaUoWYmj8FmAAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQCn3iDPoGzN
                /nQAlhei2IdOg3xNTh7SSSghLFjEBxL79vihe752H86/0qcHvvi0Y9zEBspuCtXLHHSQL1
                0nLuE2JkpC0/vmwkXXMv1//1tLcyV+7vV8xsnRtTTGd9IMb/FpmCVk8i/N6TgJJqvhPsVf
                td6q13WlqK5k/GEPVHTry8JyzA0aIGupipFeDe6W42mICvbtpjNJ3B++zWOZiAGM2MT2E9
                ROVDVFCEV3Ad+y3/vJYF+wYMxMHQIfJVJ+l+0KSqaob2nGmfakLH4VOaEagE6HwsueFcth
                t1T7KGrOHS2CRL57KLOizUBYuZgxgvYegtm3y4S0i+iIc9BHWlxJEIjpIklX0Rk8Uao0OQ
                5zc3qTqxPLQOI2IbpARlKD1IjM+0WcjgraK+9VNGQGdqL4dOCNtIAv2p4eRLVroNODZDK0
                4rWqQbFI1kahhrtyOh6vyOtgaL6p/9+qSLkHZ81rEuvdBN8zWnc1k7OXXQvELgA/UygziW
                fptmGUXB6XS1MAAAWQx+QJ7nKC/svihFQp1wAWh5SzFEvP35JwsR8KEHXCfdxJMnadx9cL
                wngnhTIZ0vJAzmr4R2Yq+GE8bGVRUh89MqZanv9rmk1ic9y6DZTl2kgw2sx13er8C9HzVL
                6b9VAPUSvjfAvMYufsPGdxSjFMghdMqiTytwvtj+K56ONy1nxL1EysWmK0oxZzYzMl+G/8
                3CzLEl724WxTtEQ9qcRF11hK28r58FCATIms+h9WVxWuh786giYdAsK5iKDnpcFsIm39tn
                y7oynWNsdM2VbZS3tSbF0kyGegfNHEEA0PLYvWXEFpX3Lom7NctvrF3gI/ezlCCF8Nx9TZ
                q7UA95f8WNxFQcynqCt9gf//35AzUif+iUegu/OGnQ59xL8miW4vXahRjjM7zsZuviPYJT
                NfQQ0ikN+obIG3+VD8hSLqod1C61rjwwptG+E+Ns6sGJzukxFNxRffUnDOZjCbxg3wSWFl
                jAKev0WsKVJuaKfavkmeC7IiTcTAwXyzVi7BxoN/NSwylKtQMrUs6/EkALhpP2jPqZ4Xpo
                7pkxZflymd7my+azz3gKjHN0HRuNlA/KJfi1iPbv2UKAbA002/d+bQ34GbD3fz4ISOxleJ
                M0Uqsnr1BUQd9KqGm5Cx3bsUj82YKE+dGFQnAypHTfCuSTwjQX4ppM04ZhbUlJbDjGU+U8
                BoTlujmUFCqFrSiQuPdkYDg32hYdHP7mYNGaX/dNCMkXOyB6aFvzYKuGzH7ZckV32Tb7By
                jdQQ43JzUed7fopzEKlyzWD+t6dtcBNDGKDUXDZfUKSAK2J4ah50swryp5wmlEL+eLnJbV
                N8r3lSaxuqsOKYeH4j+Z2wVl4VYQo29mmMKT5XVP3TIdPNR9Ym2t3On+ecro5cKJJXhCGk
                2hPZ1smHwUknMlxsSR2d1URFzxVJH9YPcGPtcIGiCi5BxHooNTGk8jFIwG04VKhdFkITm5
                ijKzqN1fpnMP3j+WIAAG1S5JnJbGVPKaSDX4HdhIcOlxJNXyxIA1u1wLISFpD/J3c+Suek
                u338ev631BIlCJ93WihuclltalW6QmaI2nOuVjFI4xHknpjcqBSKh/wdI43anhOw5l301Y
                /1eDOt9ORGlr6Pc548iMJkL+MXIaFSBdNzPO9afErFVxHeMvDI/7Ea0PrKVwwVXPq5v7kJ
                GFt0KmCHe6Sb7BEnEvC3qwlcakIpAqXhoylkHKuLcw29IACQCvRkk1b9yyLK99AB6Lo4Pz
                Me5Abw4bNqEmcmSNTmSfyw83wm5xBZDrFqs34p6C+xhYzFWmi98GMPJl/eJCEWRDZuStgs
                fO9cm41HTxGtg0hcPAWdmnRrSHB6Oi69VzMZ5sZnVLj/GgHasZ3pLbE3YlVHJ3NWD1+/D7
                gcjF0gYMckB/F8HAbJDoE6fW/ennfItRiOcVksFAminG7gBYEPY9+RN+MUDhN08k9HgyYg
                x29Jb8dZgVgRR+59IQI8+U2Z46dMJEmGKPFqiglTvmpE4RXDMKGlT0AgPOrn0OUr44Qsak
                h5fOt/HcsK1L6xthdkcXHsaxBV2I/TTxvF3BJIYv1cg6Yu45GgaeGweK9B/Eh4F09pO/qE
                HlNvTudSPUocV5meObTz1vXgc/xeDz/XLp0dAE1bv4LC6yDOhLIw1pNu03xWbZASuZXm+o
                k1FiYG1OFWDfAAM7UThh2xb+V+HjnMPK44aHJLBaNRwW+1aOlIw9M08Ijq5Xp4m0hWHpn5
                GJenLjbhpS1OeYyQSQMUswAlqVlRv2q8ODWZ1EDGWurDhhjiSgv1pe21tjSp+3kiptpA8Y
                KkCBfuQ3IaW/3b8+p3kv+fwXhgVWtZE/wC60V2rXkEL2oRtZhHLrz1u6wgsv4sbglF6FzE
                YHCQcoway8YLYw3gEJ5G14+32Ms=
                -----END OPENSSH PRIVATE KEY-----"
          script: mkdir some_folder_for_test

