name: Calendar backend workflows

on:
  push:
    branches: [ 'feature/backend_ci-cd' ]
  pull_request:
    branches: [ 'feature/backend_ci-cd' ]

jobs:

  flake8-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort flake8-quotes

      - name: Test with flake8
        run: |
          cd backend
          python -m flake8
